["POS_icon":"def_imgtypes_pos.gif",
"Advertising_icon":"def_imgtypes_pos.gif",
"Ads_icon":"def_imgtypes_pos.gif",
"Model Photography_icon":"def_imgtypes_mod_phot.gif",
"Photography_icon":"def_imgtypes_mod_phot.gif",
"Imagery_icon":"def_imgtypes_mod_phot.gif",
"Digital Photography_icon":"def_imgtypes_dig_phot.gif",
"Product Photography_icon":"def_imgtypes_dig_phot.gif",
"Photography-Lifestyle_icon":"def_imgtypes_mod_phot.gif",
"Catalog Photography_icon":"def_imgtypes_mod_phot.gif",
"HP-Product Photography_icon":"def_imgtypes_dig_phot.gif",
"HP-Other_icon":"def_imgtypes_other.gif",
"HP-Photography-Lifestyle_icon":"def_imgtypes_mod_phot.gif",
"HP-Catalog Photography_icon":"def_imgtypes_mod_phot.gif",
"OB-Product Photography_icon":"def_imgtypes_dig_phot.gif",
"OB-Other_icon":"def_imgtypes_other.gif",
"OB-Photography-Lifestyle_icon":"def_imgtypes_mod_phot.gif",
"OB-Catalog Photography_icon":"def_imgtypes_mod_phot.gif",
"Powerpoint Ready Images_icon":"def_imgtypes_dig_phot.gif",
"Product Shots_icon":"def_imgtypes_dig_phot.gif",
"Product Placements_icon":"def_imgtypes_dig_phot.gif",
"Packaging_icon":"def_imgtypes_pack.gif",
"C9 Packaging_icon":"c9_imgtypes_pack.gif",
"Logos_icon":"def_imgtypes_logos.gif",
"Logo_icon":"def_imgtypes_logos.gif",
"Cad Images_icon":"def_imgtypes_cad_images.gif",
"Cad Image_icon":"def_imgtypes_cad_images.gif",
"Icons_icon":"def_imgtypes_icons.gif",
"Other_icon":"def_imgtypes_other.gif",
"Dies_icon":"def_imgtypes_dies.gif",
"Style Guide_icon":"def_imgtypes_guides.gif",
"Style Guides_icon":"def_imgtypes_guides.gif",
"Color Block_icon":"def_imgtypes_guides.gif",
"Sell Sheets_icon":"def_imgtypes_guides.gif",
"Size Charts_icon":"def_imgtypes_guides.gif",
"Templates_icon":"def_imgtypes_guides.gif",
"Hangtags_icon":"def_imgtypes_hang.gif"]